#!/bin/bash 


NOME="buildozo"

# DEV_DIR is the directory you store your source code
# You can use an enviroment variable for this or edit it here
# DEV_DIR="/YOURDEVDIR/git/"
if [ "$DEV_DIR" == "" ];
then
    DEV_DIR = '/home/user/git/'
fi

MOUNTS=" -v $DEV_DIR:/devel/ "

echo $MOUNTS

docker rm -f $(docker ps -a -f name=$NOME -q)
docker run --name $NOME -t $MOUNTS $NOME /bin/bash


