#!/bin/bash 


NOME="buildozo"

# DEV_DIR is the directory you store your source code
# You can use an enviroment variable for this or edit it here
# DEV_DIR="/YOURDEVDIR/git/"
if [ "$DEV_DIR" == "" ];
then
    DEV_DIR='/home/user/dev/'
fi

# This will mount your dev dir and also a directory to buildozer place its stuff
MOUNTS=" -v $DEV_DIR:/devel/ -v /var/lib/buildozer:/var/lib/buildozer "

echo $MOUNTS

docker rm -f $(docker ps -a -f name=$NOME -q)
docker run --name $NOME -it $MOUNTS $NOME


